spring:
  datasource:
    url: jdbc:mysql://localhost:3306/BookDB?characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 13657064910
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming_strategy:org.hibernage.cfg.ImprovedNamingStategy